/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LogIn;


import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.DriverManager;

import DbConnection.ConnectDataBase;
import java.security.MessageDigest;
import javax.swing.JFrame;

/**
 *
 * @author Erickson Guhilde
 */
public class Login extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public Login() {
        setUndecorated(true);
        initComponents();
        
        try {
            con = db.mycon();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //setAlwaysOnTop(true);
        setResizable(false);
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        
        int x = (int) tk.getScreenSize().getWidth();
        int y = (int) tk.getScreenSize().getHeight();
        
        setSize(x,y);
        
        //Dimension size = getSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        LogText = new javax.swing.JLabel();
        UsernameTxt = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();
        Passwordtxt = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordTxtField = new javax.swing.JPasswordField();
        passCheckbox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        formPanel.setBackground(new java.awt.Color(246, 232, 250,200));
        formPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        formPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        formPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LogText.setText("Log In");
        formPanel.add(LogText, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 22, -1, -1));

        UsernameTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameTxt.setText("Username *");
        formPanel.add(UsernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, -1));

        usernameTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usernameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTxtFieldFocusLost(evt);
            }
        });
        usernameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtFieldActionPerformed(evt);
            }
        });
        formPanel.add(usernameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 370, 50));

        Passwordtxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Passwordtxt.setText("Password *");
        formPanel.add(Passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, -1));

        loginBtn.setBackground(new java.awt.Color(0, 74, 173));
        loginBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Log In");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        formPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 340, 44));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Not registered yet? Create a");
        formPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("new account");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        formPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 90, -1));

        passwordTxtField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        formPanel.add(passwordTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 370, 50));

        passCheckbox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passCheckbox.setText("Show Password");
        passCheckbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passCheckboxActionPerformed(evt);
            }
        });
        formPanel.add(passCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erickson Guhilde\\OneDrive\\Documents\\NetBeansProjects\\InventorySyst\\src\\LogIn\\bgmain.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(555, 555, 555)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1540, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here
        SignUp sign = new SignUp();
        sign.setVisible(true);

        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
         String Username, Password, pword, query, passDb = null;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://127.0.0.1:3306/inventory_system";
           SUser = "root";
           SPass = "";
           int notFound = 0;
        
        try {
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
           
           Statement st = con.createStatement();
           if("".equals(usernameTxtField.getText())){
           JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Error", JOptionPane.ERROR_MESSAGE);
           } else if("".equals(passwordTxtField.getText())){
            JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error", JOptionPane.ERROR_MESSAGE);
        
        } else {
            Username = usernameTxtField.getText();
            Password = passwordTxtField.getText();
            
               
               query = " SELECT * FROM user_info WHERE username= '"+Username+"'";
               ResultSet rs = st.executeQuery(query);
               
               
               while(rs.next()) {
                  passDb = rs.getString("password");
                 
                   notFound = 1;

               }
               if (notFound == 1 && Password.equals(passDb)){
                   
                   Stocks stock = new Stocks();
                   stock.setVisible(true);
                   dispose();
                  
               } else{
                JOptionPane.showMessageDialog(new JFrame(), "Incorrect Username or Password", "Error", JOptionPane.ERROR_MESSAGE);   
               }
               passwordTxtField.setText("");
               
            
        }
        
        }catch (Exception e){
            System.out.println("Error!" + e.getMessage());
        }
    }//GEN-LAST:event_loginBtnActionPerformed
   
    /*public static String passwordHash(String password)
    {
        
        try {
            
            MessageDigest md = MessageDigest.getInstance("SHA");
            md.update(password.getBytes());
            byte[] rbt=md.digest();
            StringBuilder sb=new StringBuilder();
            
            for(byte b: rbt)
            {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
                    
         } catch (Exception e) {
        }
        return null;
    } */
    
    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO add your handling code here:

        /*Stocks dash = new Stocks();
        dash.setVisible(true);

        dispose();*/
    }//GEN-LAST:event_loginBtnMouseClicked

    private void usernameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtFieldActionPerformed

    private void usernameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFieldFocusLost
        // TODO add your handling code here:

        if(usernameTxtField.getText().equals("")) {

            usernameTxtField.setText("Enter Username");
            usernameTxtField.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_usernameTxtFieldFocusLost

    private void usernameTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFieldFocusGained
        // TODO add your handling code here:

        if(usernameTxtField.getText().equals("Enter Username")) {

            usernameTxtField.setText("");
            usernameTxtField.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_usernameTxtFieldFocusGained

    private void passCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passCheckboxActionPerformed
        // TODO add your handling code here:
        
        if(passCheckbox.isSelected()){
            passwordTxtField.setEchoChar((char)0);
        } else{
            passwordTxtField.setEchoChar('*');
        }
    }//GEN-LAST:event_passCheckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogText;
    private javax.swing.JLabel Passwordtxt;
    private javax.swing.JLabel UsernameTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JCheckBox passCheckbox;
    private javax.swing.JPasswordField passwordTxtField;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables
}
